import type { DemoPalette, DemoSlug } from '../../config/demos';
import type { IconName } from '../../types/content';

/*
 * ============================================================================
 * WHAT A DEMONSTRATION SITE IS MADE OF
 * ============================================================================
 *
 * The shape of one fictional business's website. Five modules implement it, one template
 * renders it, and one guard suite checks that none of them invented evidence.
 *
 * ## The one rule this type exists to enforce
 *
 * **Invent the business. Never invent the evidence.**
 *
 * A demonstration site has to look like a real business or it demonstrates nothing — so a
 * name, a phone number, a service list and a service area are all fair. What is not fair
 * is proof: reviews, ratings, testimonials, licence numbers, "family owned since 1998",
 * awards, guarantees, response-time promises. Every one of those is a claim a reader would
 * weigh, and manufacturing them on the domain of a business whose entire pitch is that it
 * fabricates nothing would cost more than the demos are worth.
 *
 * So there is no `reviews` field, no `rating`, no `credentials`, no `yearsInBusiness` and
 * no `guarantee` below — and there is deliberately nowhere to put one. A future edit that
 * wants them has to change this file first, which is the point at which somebody has to
 * think about it. `demos.test.ts` sweeps the rendered strings as well, because a
 * testimonial can always be smuggled into a paragraph.
 *
 * ## Photographs: licensed, generic, and never presented as this business's jobs
 *
 * An earlier revision of this file said "no demo is ever showing a photograph of a job
 * nobody did", reasoning from two facts that were true at the time: there was no licensed
 * imagery, and the evidence rule seemed to forbid work photos outright. The first fact
 * changed — every image now comes from `scripts/media.manifest.json` with its licence and
 * author recorded in `docs/MEDIA-CREDITS.md` — and the second was drawn too wide. Stock
 * photography that *illustrates a kind of work* is what real trade businesses publish
 * too; what would be fabricated evidence is a caption claiming a photograph as this
 * business's own project, customer, crew or neighbourhood. So `DemoImage.alt` describes
 * what is visible and nothing more: no "our work in Kirkland", no before/after pairs, no
 * named jobs. `demos.test.ts` sweeps alt text with the same regexes as every other string.
 *
 * ## Why phone numbers are typed as a template
 *
 * `555-01xx` is the block reserved for fiction. A demo carrying a dialable number is a
 * demo that sends a stranger's misdial to a real person, forever, from a page that says
 * "not a real business" at the top of it.
 * ============================================================================
 */

/** A phone number in the fictional range. `(206) 555-0142`, and nothing else. */
export type FictionalPhone = `(${number}) 555-01${number}`;

/**
 * One licensed photograph, as the template renders it.
 *
 * `src`/`srcset` are Vite asset imports from `src/assets/demos/` — content-hashed, so
 * they ride the immutable cache — generated by `scripts/fetch-media.ts` from the
 * manifest. `width`/`height` are the intrinsic pixels of `src`, which the template puts
 * on the element so the browser reserves the box before the bytes arrive (CLS 0).
 *
 * `alt` is copy and is swept by the fabricated-proof guards: it describes what is
 * visible, and never claims the photograph as this business's job, customer or crew.
 */
export interface DemoImage {
  readonly src: string;
  /** `url w, url w` pairs for the WebP variants — the `<img>`'s own srcset. */
  readonly srcset: string;
  /** The AVIF `<source>` of the `<picture>`. Smaller than the WebP for every photo. */
  readonly avifSrcset: string;
  readonly alt: string;
  readonly width: number;
  readonly height: number;
}

/**
 * The one ambient clip a demo may carry, rendered below the fold.
 *
 * Muted, looped, `preload="none"`, poster-first, and never attached at all for
 * `prefers-reduced-motion` users — see `DemoAmbient`. Trades without a clip that fit the
 * byte budget and the region simply omit this: a static photograph beats a compromised
 * video, which is a finding, not a shortcut (`docs/DEMO-QUALITY-UPGRADE.md` §3).
 */
export interface DemoVideo {
  readonly src: string;
  /** A dedicated 16:9 cut, because a poster from another slot's aspect gets stretched. */
  readonly poster: string;
  readonly width: number;
  readonly height: number;
  /** What the section heading says above the clip. */
  readonly heading: string;
  /** One line under the heading. Description, never a claim. */
  readonly body: string;
}

/** One service the fictional business sells. */
export interface DemoService {
  readonly id: string;
  /** What the customer calls it, not what the trade calls it. */
  readonly name: string;
  /** One line, on the card. */
  readonly summary: string;
  /** The fuller description, on the services page. */
  readonly detail: string;
  /** Three or four specifics. What is actually done. */
  readonly includes: readonly string[];
  readonly icon: IconName;
  /** A photograph of this kind of work, on the services page. Optional by design. */
  readonly image?: DemoImage;
  /**
   * Whether this is the job the customer is calling about right now.
   *
   * Drives the emergency treatment on the trades that have one. `false` everywhere for
   * landscaping, which has no emergencies, and that difference is the point of having
   * five demos rather than one.
   */
  readonly urgent: boolean;
}

/** One question on the fictional quote form. */
export interface DemoFormField {
  readonly id: string;
  readonly label: string;
  readonly type: 'text' | 'tel' | 'email' | 'select' | 'textarea';
  /** Present for `select` only. */
  readonly options?: readonly string[];
  readonly required: boolean;
  readonly hint?: string;
}

export interface DemoSite {
  readonly slug: DemoSlug;
  /**
   * Always true, always rendered, never optional.
   *
   * The disclosure bar reads this rather than assuming, so the one thing that cannot
   * happen is a demo that renders without saying it is one.
   */
  readonly isFictional: true;

  /** The fictional business. */
  readonly business: {
    readonly name: string;
    /** The two-or-three-word thing they do, for the header lockup. */
    readonly trade: string;
    /** Initials or a short mark. No logo files. */
    readonly mark: string;
    readonly phone: FictionalPhone;
    readonly email: string;
    /** Neighbourhoods. Never a street address — see the note at the top of this file. */
    readonly serviceAreas: readonly string[];
    readonly hours: readonly { readonly days: string; readonly time: string }[];
  };

  readonly palette: DemoPalette;

  /**
   * The demo's photography and, for some trades, one ambient clip.
   *
   * Asset imports live in the trade's own content module, so every byte of this rides
   * the trade's lazy chunk — the same argument that keeps these modules out of
   * `content/index.ts`.
   */
  readonly media: {
    /** The homepage hero. The page's LCP element: eager, `fetchpriority="high"`. */
    readonly hero: DemoImage;
    /** Finished-work strip on the homepage. Three images; landscaping runs larger. */
    readonly gallery: readonly DemoImage[];
    /** Beside the homepage's closing block. */
    readonly closing: DemoImage;
    /** Ambient below-the-fold clip. Absent where no clip earned its bytes. */
    readonly ambient?: DemoVideo;
  };

  readonly home: {
    readonly eyebrow: string;
    /** The headline. Says what they fix and where — not "Quality You Can Trust". */
    readonly heading: string;
    readonly subheading: string;
    /**
     * Which hero the template paints.
     *
     * `split` for the emergency trades: copy and a dominant call action beside the
     * photograph. `immersive` for the considered purchases (roofing, landscaping): the
     * photograph full-bleed behind a scrim, quote action first, phone second. The
     * research behind the flip is in `docs/DEMO-QUALITY-UPGRADE.md` §3.
     */
    readonly heroLayout: 'split' | 'immersive';
    readonly primaryAction: string;
    readonly secondaryAction: string;
    /** Three short reassurances. Facts about the work, never proof claims. */
    readonly points: readonly string[];
    readonly servicesHeading: string;
    readonly servicesLede: string;
    /** Above the finished-work strip. Descriptive — "the kind of work", never "our jobs". */
    readonly galleryHeading: string;
    readonly galleryLede: string;
    readonly areaHeading: string;
    readonly areaLede: string;
    readonly closingHeading: string;
    readonly closingBody: string;
  };

  readonly services: {
    readonly heading: string;
    readonly lede: string;
    readonly items: readonly DemoService[];
    /** What happens when the job is not on the list. */
    readonly note: string;
  };

  readonly contact: {
    readonly heading: string;
    readonly lede: string;
    readonly formHeading: string;
    readonly formLede: string;
    readonly fields: readonly DemoFormField[];
    readonly submitLabel: string;
    readonly callHeading: string;
    readonly callLede: string;
  };
}
