import { site } from './site';
import type { TradeSlug } from '../config/trades';

/*
 * ============================================================================
 * THE WEBSITE REVENUE AUDIT
 * ============================================================================
 *
 * The PlayBook's 40-point assessment already scored twenty categories, produced a band
 * and ranked the weakest five — and then stopped, offering the reader a link back to the
 * improvement they had just scored themselves badly on. It was a diagnosis with no
 * consequence attached and no way to act on it.
 *
 * This is that assessment finished. Same twenty categories, same scoring, same weakest
 * five — plus the trade it is being read for, a diagnosis written in the owner's terms
 * rather than in UX terms, the arithmetic on their own numbers, and a way to send the
 * whole thing to somebody who can act on it.
 *
 * ## Why it is not on `/playbook`
 *
 * Because `playbook.scorecard.storageNote` promises, in rendered copy pinned by a test,
 * that the assessment's answers "stay in this browser and are never sent anywhere". That
 * is true of the PlayBook assessment and must stay true. An audit that submits its
 * results is a different promise, so it is a different surface with its own consent line
 * and its own storage key. The PlayBook keeps its promise; the audit makes its own.
 *
 * ## The rules on the numbers
 *
 *   1. **No currency figure appears in this file.** `content.test.ts` sweeps the content
 *      layer and fails on any that is not a published price. Every figure the audit shows
 *      is computed at runtime from what the visitor typed, which is also the only way any
 *      of it is worth reading.
 *   2. **The scenario is driven by a lever the visitor moves.** They choose how many more
 *      enquiries a month to model. Nothing here predicts a number, because nothing here
 *      could — and a projection generated by the seller is the exact move that makes a
 *      sceptical owner close the tab.
 *   3. **Every output is labelled illustrative, next to the output rather than in a
 *      footer.** The word appears in the panel heading, not only in the disclaimer.
 *   4. **No claim that the recommended work produces the modelled outcome.** The scenario
 *      shows what a conversion change is worth. It does not say a redesign causes one.
 * ============================================================================
 */

export const audit = {
  name: 'Website Revenue Audit',

  hero: {
    eyebrow: 'Free, and you keep the answer',
    heading: 'Find out where your website is losing the work.',
    lede: 'Twenty checks, about five minutes, and no email address needed to see the result. You score your own site, and it comes back with the five things costing you the most — what each one is doing to a customer, and what I would change first.',
    supporting:
      'At the end you can put your own numbers against it and see what a few more enquiries a month would actually be worth. Nothing is sent anywhere unless you decide to send it.',
    /*
     * There is no `startLabel` here any more. It was written for a "Start the audit"
     * button the page never grew, because the audit is one page rather than a wizard — the
     * first question is already on screen, and a button that scrolls to something visible
     * is a button that costs a tap to do nothing.
     */
  },

  /* ---------------------------------------------------------------- step 1: trade */

  trade: {
    stepLabel: 'Step 1',
    heading: 'What kind of business is this?',
    lede: 'It changes the diagnosis. A furnace that has failed and a roof being replaced are not the same sale, and the website should not be the same shape for both.',
    fieldLabel: 'Your trade',
    hint: 'Pick the closest. If none of them fit, the last option is not a lesser answer — most local service businesses are not in the five named trades.',

    /*
     * Shown once a trade with a page of its own is chosen. It is a link out of a form,
     * which normally costs conversions — and is right here, because the reader has just
     * told the page which of five arguments is the one written for them, and the audit
     * keeps their answers while they go and read it.
     */
    pageLinkIntro: 'There is a page on this trade specifically:',
  },

  /* ------------------------------------------------------------ step 2: assessment */

  assessment: {
    stepLabel: 'Step 2',
    heading: 'Score your website',
    lede: 'Twenty categories, two points each. Score it as you find it today rather than as you mean it to be — the point is to find the weak ones, and a kind score produces a useless list.',
    instructions:
      'Open your own site on a phone while you do this, on mobile data rather than your office wi-fi. That is the condition your customers are in.',
    progressLabel: 'scored',
    resetLabel: 'Clear my answers',
    storageNote:
      'Your answers stay in this browser while you work. Nothing leaves it unless you choose to send the audit at the end, and you can clear everything with the button above.',
  },

  /* ------------------------------------------------------------- step 3: diagnosis */

  diagnosis: {
    stepLabel: 'Step 3',
    heading: 'What that is costing you',
    lede: 'Your five weakest categories, weakest first. Each one is written as what it does to somebody trying to hire you, rather than as the name of a design problem.',
    incompleteHeading: 'Score all twenty to see the diagnosis',
    incompleteBody:
      'A partial score would rank whichever categories you happened to answer first, which looks like an answer while being worse than none.',
    perfectHeading: 'Nothing scored below two',
    perfectBody:
      'Either the site is in genuinely good shape or the scoring was generous. Either way the next move is measurement rather than another list: find out what visitors actually do, then change things on evidence.',

    /*
     * The band's caveat, which this page was missing while the PlayBook carried it.
     *
     * The bands rendered here are the *same objects* the PlayBook renders — `bandFor()`
     * resolves them from `playbook.scorecard.bands` — and there they sit under
     * `scorecard.disclaimer`, which says plainly that nobody has calibrated them against
     * anybody's revenue. Here they appeared under the heading "What that is costing you"
     * with nothing attached, which is the one place on this site a borrowed, uncalibrated
     * verdict could read as a measurement. The scenario below is labelled illustrative in
     * two places; the diagnosis above it was not labelled at all.
     */
    /*
     * ======================================================================
     * WHERE THE ASSESSMENT LEADS
     * ======================================================================
     *
     * The audit used to end here. Somebody scored twenty categories, read five findings,
     * and was offered a form — with nothing connecting what they had just learned about
     * their own site to what is actually for sale. It was the best asset on the site and
     * it pointed nowhere.
     *
     * This is a recommendation made from the reader's own answers, which is the only kind
     * worth printing. A pricing page that recommends the middle tier to everybody is one
     * every reader has seen and correctly ignores.
     *
     * `none` is the branch that makes the other two credible: a site scoring above 85%
     * probably does not need rebuilding, and being told so by the person selling rebuilds
     * is the whole argument for believing anything else on the page.
     * ======================================================================
     */
    recommendation: {
      heading: 'Where I would start, based on what you just scored',
      /** Interpolated with the tier name. */
      lead: 'On these answers, the work I would suggest is',
      note: 'That is a starting point from a self-assessment, not a quote. What it actually needs comes from looking at the real site, which is the next step and costs nothing.',
      seePricing: 'See what that includes',
      none: {
        heading: 'You probably do not need a rebuild',
        body: 'You scored well enough that a new website is unlikely to be the thing holding you back. The honest next move is measurement rather than construction: find out where the enquiries you already get are coming from, and fix the two or three specific things above. If you want a second opinion on that, ask — and if the answer is still "leave it alone", that is what I will tell you.',
      },
    },

    bandDisclaimer:
      'This is a self-assessment, and the bands are a way of ordering what to do next rather than a validated benchmark — nobody has calibrated them against anybody’s revenue. What is useful here is which categories came out weakest, not the number itself.',

    /** The four beats of every finding. Labels, so the shape is visible on the page. */
    labels: {
      behaviour: 'What a customer does',
      consequence: 'What that costs you',
      improvement: 'What I would change',
    },

    scoreLabel: (score: number) => `Scored ${score} out of 2`,
  },

  /* ----------------------------------------------------------- step 4: your numbers */

  funnel: {
    stepLabel: 'Step 4',
    heading: 'Now put your own numbers against it',
    lede: 'Optional, and every field has an "I don’t know" — most owners do not have these to hand, and guessing badly is worse than leaving it blank. Whatever you fill in stays in this browser.',

    unknownLabel: "I don't know",

    fields: {
      visitors: {
        label: 'Visitors to your website in a month',
        hint: 'A rough number is fine. If you have analytics installed, it is the one number it definitely shows you.',
      },
      enquiries: {
        label: 'Calls and quote requests from the website in a month',
        hint: 'The ones you can actually attribute to the site. If you have never counted, that is worth knowing on its own.',
      },
      closeRate: {
        label: 'Of those, how many become customers',
        hint: 'As a percentage. Most owners know this one better than they expect.',
        suffix: '%',
      },
      jobValue: {
        label: 'What an average job is worth to you',
        hint: 'The finished job, not the enquiry. Before costs is fine — it only needs to be roughly right.',
      },
    },

    /*
     * The lever. The visitor chooses the improvement to model, which is the whole reason
     * this is defensible: the number on screen is arithmetic on their assumption rather
     * than a forecast produced by the person selling them something.
     */
    lever: {
      label: 'Model a few more enquiries a month',
      hint: 'Move this to whatever you think is realistic. It is your assumption, not my estimate.',
      unit: 'more enquiries a month',
    },
  },

  /* ------------------------------------------------------------- step 5: scenario */

  scenario: {
    stepLabel: 'Step 5',
    heading: 'Illustrative scenario',
    lede: 'Arithmetic on the numbers you just entered. It is not a forecast, not a projection, and not a claim about what any particular piece of work would produce.',

    currentHeading: 'Where you are now',
    changeHeading: 'If that changed',

    labels: {
      visitors: 'Visitors',
      enquiries: 'Enquiries',
      customers: 'Customers',
      value: 'Value of that work',
      rate: 'Enquiry rate',
      additionalCustomers: 'Additional customers',
      additionalValue: 'Additional value',
      perYear: 'Over a year',
    },

    emptyHeading: 'Add a couple of numbers to see this',
    emptyBody:
      'The scenario needs at least how many enquiries you get and what a job is worth. Without those it would be arithmetic on invented figures, which is what this page exists not to do.',

    /*
     * The disclaimer. Rendered next to the numbers rather than beneath the page, because
     * a caveat somebody has to scroll to is a caveat written for the seller's comfort.
     *
     * The last clause names the offer in full, and has to. This page is itself a
     * self-assessment — the word is used in that sense four times above — so "what the
     * assessment is for" would point the reader at the twenty questions they have just
     * finished rather than at the thing being offered. Interpolated so it stays the same
     * name the button uses.
     */
    disclaimer: `Illustrative scenario, not a forecast. These are your own figures multiplied together, using an improvement you chose. Nothing on this page claims that a website change produces that improvement — whether the website is what is holding your enquiries back is exactly what the ${site.offer.freeReview.name.toLowerCase()} is for.`,

    note: 'A scenario is not a promise, and no work has been quoted here.',
  },

  /* ------------------------------------------------------------------ step 6: send */

  send: {
    stepLabel: 'Step 6',
    heading: 'Want me to go through it properly?',
    lede: 'Send the audit over and I will look at the actual site rather than the score — the five weakest categories are where I would start, and I will tell you which of them I think is genuinely costing you work and which is cosmetic.',
    freeNote:
      'Free, no obligation, and you keep everything above whether or not you send it. If I think the website is not what is holding the business back, that is what you will get back from me.',

    fields: {
      name: { label: 'Your name' },
      businessName: { label: 'Business name' },
      email: { label: 'Email' },
      phone: { label: 'Phone', hint: 'The best number to reach you on.' },
      website: {
        label: 'Your website',
        optionalLabel: 'optional',
        hint: 'Leave blank if you do not have one yet.',
        placeholder: 'example.com',
      },
    },

    /*
     * The consent line. Says exactly what is transmitted, because what is transmitted is
     * more than an email address — it is the whole audit, and somebody who scored their
     * own site harshly deserves to know that is what they are sending.
     */
    consent:
      'Sending this shares your answers, your five weakest categories and any numbers you entered, along with your contact details, so I can reply about them. Nothing else, and there is no mailing list to be added to.',

    submit: { idle: 'Send my audit', pending: 'Sending…' },

    success: {
      heading: 'Sent.',
      body: 'I have got your audit and I will come back to you directly. If it is urgent, calling is faster than waiting for a reply.',
    },

    failure: {
      heading: 'That did not send',
      body: 'Nothing has been sent and nothing you entered has been lost. Try again in a moment, or use the phone number or email address at the bottom of the page — those always work.',
    },

    errorSummary: { heading: 'Please check the following' },
  },

  /* ------------------------------------------------------------------ the summary */

  /** Labels used to render the audit into the message field of the lead submission. */
  summary: {
    title: 'Website Revenue Audit',
    tradeLabel: 'Trade',
    scoreLabel: 'Score',
    bandLabel: 'Band',
    weakestLabel: 'Weakest categories',
    funnelLabel: 'Their numbers',
    notProvided: 'not provided',

    /*
     * What an unfinished audit reports instead of a score.
     *
     * A running total against the full maximum is not a score — it is the sum of what has
     * been answered, and printing "10/40" for somebody who scored five categories at full
     * marks tells the owner the opposite of the truth at the exact moment they are
     * deciding which lead to open.
     */
    partial: (answered: number, total: number) =>
      `not finished — ${answered} of ${total} categories scored, so there is no total yet`,
  },

  closing: {
    heading: 'Or just do the work yourself',
    body: 'Everything the audit is built on is published in full in the PlayBook — twenty improvements, what goes wrong in each, and a test you can run on your own site in five minutes. No email address required to read any of it.',
  },
} as const;

/* ------------------------------------------------------------------ diagnosis copy */

/*
 * The missing half of a finding.
 *
 * A `PlaybookPrinciple` already carries what goes wrong (`uxProblem`), what it costs
 * (`consequence`) and what to do (`principle` + `practices`). What it has never carried
 * is the middle beat: what the customer actually *does* when they hit it. That is the
 * sentence an owner recognises, because it describes somebody standing in their driveway
 * rather than a category of design problem.
 *
 * Keyed by scorecard category id, which is identical to the principle id for all twenty.
 */
export const behaviourByCategory: Readonly<Record<string, string>> = {
  'local-relevance':
    'They cannot tell whether you come out to where they live, so they go back and pick somebody who said so.',
  'search-intent':
    'They never arrive at all. The words they typed are not the words on your pages, so your site was not among the ones they saw.',
  clarity:
    'They spend a couple of seconds trying to work out what you sell, do not manage it, and close the tab.',
  'first-screen':
    'They land, see a photograph and a slogan, and have to scroll to find out whether they are in the right place. Some of them do not.',
  hierarchy:
    'They scan the page, find nothing pulling their eye anywhere in particular, and read none of it properly.',
  navigation:
    'They go looking for the service they came for, do not find it in one move, and give up on a menu rather than on you — which amounts to the same thing.',
  speed:
    'They wait, watching a blank screen, and go back to the results page before your page has finished arriving. You never hear about it.',
  mobile:
    'They pinch, zoom, mis-tap something, and decide the whole thing is more effort than calling the next result.',
  accessibility:
    'They cannot read the grey text in daylight, or cannot operate the form, and abandon something they had already decided to do.',
  colour:
    'They cannot see which thing on the page is the thing to press, because five things are all competing to be it.',
  trust:
    'They are deciding whether to let a stranger into their house, find nothing on the page they could check, and call somebody who gave them a reason.',
  proof:
    'They read the claim, have no evidence for it in front of them, and carry the doubt to the next site instead of to your phone.',
  expectations:
    'They hover over the form wondering what happens if they fill it in, who calls, when, and whether it costs anything — then decide to think about it later.',
  cta: 'They have decided to get in touch and cannot immediately see how, which is the most expensive moment on the whole site to lose somebody.',
  forms:
    'They start the form, reach the field asking for their budget or how they heard about you, and stop.',
  'service-pages':
    'They find a bulleted list with the job they need somewhere in it, and nothing that convinces them you do that particular work well.',
  friction:
    'Nothing stops them exactly. They just meet one more small obstacle than they were willing to, and leave without either of you knowing why.',
  'message-match':
    'They click your advert, land somewhere that does not repeat what it promised, and leave — and you paid for the click.',
  measurement:
    'Nothing happens to them. It happens to you: every decision about the site becomes a guess, and you cannot tell a good month from a lucky one.',
  'continuous-improvement':
    'They compare you with a competitor whose site was updated this season and yours which was not, and draw a conclusion about which business is busier.',
};

/*
 * Trade overlays.
 *
 * Only where the trade genuinely changes the answer. Speed, contrast and colour do not
 * care what you do for a living, and inventing a plumbing-specific sentence about colour
 * contrast would be padding that makes the whole diagnosis less credible. What does
 * change is anything touching urgency, evidence and what the customer is afraid of.
 *
 * Anything not overridden falls through to `behaviourByCategory`.
 */
export const tradeBehaviour: Readonly<
  Partial<Record<TradeSlug, Readonly<Record<string, string>>>>
> = {
  hvac: {
    cta: 'It is cold, or it is too hot, and they have decided to call somebody in the next few minutes. If the number is not in front of them they will call whoever put theirs there.',
    expectations:
      'They want to know whether anybody can come out today. Not saying so is the difference between the call and the next search result.',
    trust:
      'They are letting somebody into the house to work on a system they cannot evaluate. Licence, insurance and a real name matter more here than a photograph of a van.',
    'first-screen':
      'They are looking for one thing: can you fix this, and when. A first screen that opens on company history is answering a question nobody asked.',
  },
  plumbing: {
    cta: 'There is water where water should not be. Anything between them and a phone call is competing with a genuine emergency, and losing.',
    expectations:
      'They want to know how fast somebody can be there and roughly what a call-out costs. Silence on both reads as expensive.',
    'service-pages':
      'A burst pipe and a bathroom remodel are two different customers. A single services page makes both of them work out whether you mean them.',
    'first-screen':
      'The emergency and the planned job need separating in the first screen, or the urgent customer has to read past a kitchen renovation to find you.',
  },
  roofing: {
    cta: 'Nobody books a roof from a phone in a hurry. The action they want is an inspection or an estimate, and asking them to "get in touch" instead loses the ones who were ready.',
    trust:
      'This is a large purchase they cannot judge, so they are looking for licence, insurance, bonding and photographs of finished roofs. Absent evidence is not neutral here — it is a reason to keep looking.',
    proof: 'They want to see roofs you have finished, near them, in the weather they get.',
    expectations:
      'They want to know whether the inspection is free, how long the quote takes, and whether there is a way to spread the cost. Every unanswered one is a reason to get a fourth quote instead of accepting yours.',
  },
  landscaping: {
    cta: 'They have been looking at photographs and imagining their own garden. The next step they want is somebody coming to look at it, not a general enquiry form.',
    proof:
      'This is a decision made with the eyes. Photographs of finished work are the argument, and everything else is a caption.',
    'service-pages':
      'A one-off garden redesign and a regular mowing round are different sales to different customers, and a single list makes both of them guess which one you want.',
    trust:
      'They are giving somebody access to their property, often while they are out. A named person and a real service area do more work here than credentials.',
  },
  electrical: {
    cta: 'Urgent faults and planned work need different actions. One button labelled "contact us" serves the planned customer badly and the urgent one not at all.',
    trust:
      'Licensing is not a credential here, it is the whole question. A licence number a customer can check is worth more than any amount of copy about quality.',
    expectations:
      'They want to know whether the work needs an inspection, a permit, or a return visit. Not saying makes a small job feel like a project.',
    'service-pages':
      'Panel upgrades, EV chargers and a dead socket are three different searches. A page each is how any of them find you.',
  },
};

/** Resolves the behaviour line for a category, honouring the trade overlay. */
export function behaviourFor(categoryId: string, trade: TradeSlug): string {
  return tradeBehaviour[trade]?.[categoryId] ?? behaviourByCategory[categoryId] ?? '';
}
